# Generated by Django 3.2.7 on 2021-09-25 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210502_0557'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='publish',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
