# Generated by Django 3.2.7 on 2021-09-25 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_text_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='publish',
            field=models.BooleanField(default=False),
        ),
    ]
